version: 2
updates:
  # Maintain dependencies for go-modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "github.com/khulnasoft/tunnel" ## `tunnel` are updated manually
    groups:
      docker:
        patterns:
          - "github.com/docker/*"
      common:
        exclude-patterns:
          - "github.com/khulnasoft/tunnel"
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
